GET http://localhost:8080/rooms/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZSIsIl9pZCI6IjYyNzFiMGZmYTJiNGM4MzNlYjVmODE2OSIsImlhdCI6MTY1MTYxOTE2NiwiZXhwIjoxNjUxNjIyNzY2fQ.ONqmLu_JVEPQhapGMuxVdX_L9FpwDukiZ_YlyOxgEHU

###

POST http://localhost:8080/rooms/addUserToRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZTIiLCJfaWQiOiI2MjcxYjBlYmEyYjRjODMzZWI1ZjgxNjYiLCJpYXQiOjE2NTE2MjExNTYsImV4cCI6MTY1MTYyNDc1Nn0.1-b8ZQZZjPXiyXG6dwWU4t-ZwGD5bfaRIGU268Tzmxg

{
  "roomId": "6271b10ea2b4c833eb5f816c",
  "userId": "6271b0ffa2b4c833eb5f8169"
}

###


POST http://localhost:8080/rooms/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcxYjBlYmEyYjRjODMzZWI1ZjgxNjYiLCJpYXQiOjE2NTE2MTgwMjcsImV4cCI6MTY1MTYyMTYyN30.uNQ06K4l_TeD5vPAAKAyWb6E482-ArcU1NCaOFtfD_A

{
  "name": "myrooms"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "george2",
  "password": "pass"
}

###
GET http://localhost:8080/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjRmNTFhYjcxZjJlNjBjMDZmMTQ1NTEiLCJpYXQiOjE2NDkzNjU0MTksImV4cCI6MTY0OTM2OTAxOX0.xYqT4YxBSKwW0eWvXIzynvB2weXptg3J5UElfG8x1Pc

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "george",
  "email": "diamantissgiorgos@gmail.com",
  "password": "pass",
  "confirmPassword": "pass"
}

###