GET http://localhost:8080/rooms/
Accept: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZSIsIl9pZCI6IjYyNmQ3ZDJkMGQ4YWY2ODA2ODA3YzBiMCIsImlhdCI6MTY1MTQyNzM2OCwiZXhwIjoxNjUxNDMwOTY4fQ.wVv0LLGsk6cJTuskGwFn5-GoD3d7YiFCE9zyIlhpvVc

###
POST http://localhost:8080/rooms/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZTIiLCJfaWQiOiI2MjZkODU5YjMxMDcyY2IwZDhiYTRkOWEiLCJpYXQiOjE2NTE0MjY5MTYsImV4cCI6MTY1MTQzMDUxNn0.uIE6kR-tpUy7zFS_mESvMkO-ed97W0vtKyfQC3djP2c

{
  "name": "myrooms"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "george",
  "password": "pass"
}

###
GET http://localhost:8080/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjRmNTFhYjcxZjJlNjBjMDZmMTQ1NTEiLCJpYXQiOjE2NDkzNjU0MTksImV4cCI6MTY0OTM2OTAxOX0.xYqT4YxBSKwW0eWvXIzynvB2weXptg3J5UElfG8x1Pc

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "george2",
  "email": "diamantissgiorgos2@gmail.com",
  "password": "pass",
  "confirmPassword": "pass"
}

###